Fix FiltersCancellationIT flaky suite setup (#153133)
`FiltersCancellationIT.setupSuiteScopeCluster` intermittently fails
with:

```
java.lang.AssertionError: Expected all shards successful
Expected: <11>
     but: was <10>
```

This fixes that.

This also lowers the bulk size so the fix in #152690 is more likely to
kick in, beating the timeouts.

Closes #153023.